export const WEBHOOK_MODULE_OPTIONS = 'WEBHOOK_MODULE_OPTIONS';

export const OUTGOING_WEBHOOK_OPTIONS = 'OUTGOING_WEBHOOK_OPTIONS';

export const INCOMING_WEBHOOK_OPTIONS = 'INCOMING_WEBHOOK_OPTIONS';

export const WEBHOOK_EVENT_BUS = 'WEBHOOK_EVENT_BUS';

export const WEBHOOK_CIRCUIT_BREAKER = 'WEBHOOK_CIRCUIT_BREAKER';

export const WEBHOOK_DELIVERY_STORE = 'WEBHOOK_DELIVERY_STORE';

export const INCOMING_WEBHOOK_ADAPTERS = 'INCOMING_WEBHOOK_ADAPTERS';

export const INCOMING_WEBHOOK_HANDLERS = 'INCOMING_WEBHOOK_HANDLERS';

export const WEBHOOK_OUTGOING_QUEUE = 'WEBHOOK_OUTGOING_QUEUE';

export const DEFAULT_MAX_RETRIES = 5;

export const DEFAULT_BASE_DELAY_MS = 1000;

export const DEFAULT_TIMEOUT_MS = 10000;

export const DEFAULT_CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5;

export const DEFAULT_CIRCUIT_BREAKER_COOLDOWN_MS = 30000;

export const DEFAULT_CIRCUIT_BREAKER_HALF_OPEN_SUCCESS_THRESHOLD = 3;

export const DEFAULT_CIRCUIT_BREAKER_PROBE_TIMEOUT_MS = 5000;

export const DEFAULT_INCOMING_PATH = 'webhook';
